"""
CSV-based Wordalisations Database Adapter

Provides the same interface as WordalisationsDB but reads from CSV files
generated by train_wordalisations.py
"""

import csv
from typing import List, Dict, Any
from pathlib import Path


class WordalisationsCSV:
    """
    CSV adapter for wordalisations - matches WordalisationsDB interface.
    
    Reads training examples from CSV files created by train_wordalisations.py
    """
    
    def __init__(self, csv_dir: str = "."):
        """
        Initialize with directory containing CSV files.
        
        Args:
            csv_dir: Directory where function_name.csv files are stored
        """
        self.csv_dir = Path(csv_dir)
    
    def get_examples(
        self,
        function_name: str,
        limit: int = 5,
        min_quality: int = 3
    ) -> List[Dict[str, str]]:
        """
        Get examples for a function from CSV file.
        
        Args:
            function_name: Name of WORDALISE function (e.g., 'filmsBiggerMeaning')
            limit: Maximum number of examples to return
            min_quality: Minimum quality rating (not used in CSV version)
            
        Returns:
            List of {question, knowledge, answer} dicts
        """
        csv_path = self.csv_dir / f"{function_name}.csv"
        
        if not csv_path.exists():
            print(f"Warning: {csv_path} not found")
            return []
        
        examples = []
        
        try:
            with open(csv_path, 'r', encoding='utf-8') as f:
                # Detect delimiter (comma or semicolon)
                first_line = f.readline()
                f.seek(0)
                delimiter = ';' if ';' in first_line and first_line.count(';') >= 2 else ','
                
                reader = csv.DictReader(f, delimiter=delimiter)
                
                for row in reader:
                    # Map CSV columns to expected format
                    examples.append({
                        'question': row['question'],
                        'context': row['knowledge'],  # CSV uses 'knowledge', DB uses 'context'
                        'answer': row['answer']
                    })
        
        except Exception as e:
            print(f"Error loading examples from {csv_path}: {e}")
            return []
        
        # Return up to 'limit' most recent examples
        total_available = len(examples)
        examples_to_use = examples[-limit:] if len(examples) > limit else examples
        
        # Report what we're doing
        if total_available > 0:
            print(f"  📚 Using {len(examples_to_use)} most recent examples (from {total_available} available)")
        
        return examples_to_use
    
    def add_example(self, function_name: str, question: str, context: str, 
                   answer: str, **kwargs) -> None:
        """
        Add example to CSV file (appends to existing file).
        
        Args:
            function_name: Name of WORDALISE function
            question: Example question
            context: Domain knowledge (stored as 'knowledge' in CSV)
            answer: Exemplar answer
            **kwargs: Additional parameters (ignored for CSV)
        """
        csv_path = self.csv_dir / f"{function_name}.csv"
        file_exists = csv_path.exists()
        
        with open(csv_path, 'a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f, delimiter=',')
            
            # Write header if new file
            if not file_exists:
                writer.writerow(['question', 'knowledge', 'answer'])
            
            # Write data
            writer.writerow([question, context, answer])
    
    def count_examples(self, function_name: str) -> int:
        """Count examples for a function."""
        examples = self.get_examples(function_name, limit=999999)
        return len(examples)


def create_wordalisations_csv(csv_dir: str = ".") -> WordalisationsCSV:
    """
    Factory function to create CSV adapter.
    
    Args:
        csv_dir: Directory containing CSV files
        
    Returns:
        WordalisationsCSV instance
    """
    return WordalisationsCSV(csv_dir=csv_dir)
